language: java

sudo: false

install: mvn clean install -Dgpg.skip

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

notifications:
  email:
    recipients:
      - Vitaliy.Emporopulo@amdocs.com
      - Halfon.Tal@amdocs.com
